### ISSUE TITLE
Refactor: Update React imports

### ISSUE THREAD

**Issue by kenfeliciano** [kenfeliciano/koamar.com#5]
Update all React imports from
`import React from 'react'`
to
`import * as React from 'react'`

**Comment by kenfeliciano** [comment]
Yes, I realize I'll probably be the only working on this, especially at first (and perhaps forever...why wouldn't I be?) but trying to get the hang of GitHub Issues. An option is to use Azure DevOps for tracking everything but why not do it all in GitHub if possible?

**Comment by Jwright707** [comment]
I can work on this @kenfeliciano if you like? I'm also curious about the change to `import * as React from 'react'` compared to just `import React from 'react'`. Thank you and talk to you soon.

**Comment by kenfeliciano** [comment]
Hi there! You are welcome to work on this. It'll be great for me to figure out how to play well with others. It'll be my first Pull Request approval!
I've read a few things about switching to the new method for future versions of React. The Gatsby starters, and a lot of things, seem to always have the original way of doing things. [This tweet from Kent C. Dodds](https://twitter.com/kentcdodds/status/1321885232878923776) is a good reference. I tend to ***learn*** things, make a big decision like this, and then forget a lot of the details that lead me there. Thanks for reminding me!

**Comment by Jwright707** [comment]
Sounds good @kenfeliciano. I work on this tomorrow and then make a PR 👍
